"""
1. https://new.cnzz.com/v1/login.php?siteid=1280294351
2. Login with password: hass-xiaomi-miot
3. https://web.umeng.com/main.php?c=eanalysis&a=frame&siteid=1280294351#!/0/eanalysis/category/3/1280294351/2021-01-01/0
4. Search model via https://home.miot-spec.com
"""

MIOT_LOCAL_MODELS = [
    '090615.curtain.sidt82',
    'ateai.mosq.dakuo',
    'babai.curtain.190812',
    'cgllc.airm.cgdn1',
    'chuangmi.plug.212a01',
    'cubee.airrtc.th123e',
    'cuco.plug.cp2',
    'cuco.plug.cp2a',
    'cuco.plug.cp3a',
    'cuco.plug.sp5',
    'dmaker.fan.p10',
    'dmaker.fan.p11',
    'dmaker.fan.p9',
    'dooya.curtain.m1',
    'dreame.vacuum.mb1808',
    'dreame.vacuum.mc1808',
    'dreame.vacuum.p2009',
    'dreame.vacuum.p2041',
    'dreame.vacuum.p2157',
    'lumi.acpartner.mcn04',
    'lumi.curtain.hagl05',
    'mijia.vacuum.v2',
    'mmgg.pet_waterer.s1',
    'opple.light.tabcw',
    'roidmi.vacuum.v60',
    'viomi.dishwasher.v06',
    'viomi.fan.v6',
    'viomi.hood.v2',
    'viomi.vacuum.v18',
    'viomi.vacuum.v19',
    'xiaomi.aircondition.mc5',
    'xiaomi.aircondition.mc8',
    'xiaomi.aircondition.mt1',
    'xiaomi.aircondition.mt2',
    'xiaomi.aircondition.mt8',
    'yeelink.light.colorc',
    'yeelink.light.mono6',
    'yeelink.switch.sw1',
    'zhimi.airpurifier.ma4',
    'zhimi.airpurifier.mb3',
    'zhimi.airpurifier.mb4',
    'zhimi.fan.fa1',
    'zhimi.fan.fb1',
    'zhimi.fan.za5',
    'zhimi.heater.za2',
]
