CUSTOM_TEMPLATES = {
    'chuangmi_plug_v3_power_cost': "{%- set val = (result.0 | default({})).get('value',{}) %}"
                                   "{%- set day = now().day %}"
                                   "{{ {"
                                   "'today': val.pc | default(0),"
                                   "'today_duration': val.pc_time | default(0),"
                                   "'month': result[:day] | sum(attribute='value.pc'),"
                                   "'month_duration': result[:day] | sum(attribute='value.pc_time'),"
                                   "} }}",
    'lumi_acpartner_electric_power': "{%- set val = props.get('prop.ac_power',props.get('prop.load_power',0)) %}"
                                     "{{ {"
                                     "'electric_power': val | round(2),"
                                     "} }}",
    'micloud_statistics_power_cost': "{%- set dat = namespace(today=0,month=0) %}"
                                     "{%- set tim = now() %}"
                                     "{%- set stm = tim - timedelta(minutes=tim.minute,seconds=tim.second) %}"
                                     "{%- set tod = stm - timedelta(hours=tim.hour) %}"
                                     "{%- set stm = tod - timedelta(days=tim.day-1) %}"
                                     "{%- set tod = tod | as_timestamp | int(0) %}"
                                     "{%- set stm = stm | as_timestamp | int(0) %}"
                                     "{%- for d in (result or []) %}"
                                     "{%-   set t = d.time | default(0) | int(0) %}"
                                     "{%-   if t >= stm %}"
                                     "{%-     set v = (d.value | default('[]') | string | from_json) or [] %}"
                                     "{%-     set n = (v[0] | default(0)) / 100 %}"
                                     "{%-     if t >= tod %}"
                                     "{%-       set dat.today = n %}"
                                     "{%-     endif %}"
                                     "{%-     set dat.month = dat.month + n %}"
                                     "{%-   endif %}"
                                     "{%- endfor %}"
                                     "{{ {"
                                     "'power_cost_today': dat.today | round(3),"
                                     "'power_cost_month': dat.month | round(3),"
                                     "} }}",
    'midr_rv_mirror_cloud_props': "{%- set sta = props.get('prop.Status',0) | int %}"
                                  "{%- set pos = props.get('prop.Position','{}') | from_json %}"
                                  "{%- set tim = pos.get('up_time_stamp',0) | int %}"
                                  "{{ {"
                                  "'prop.status': sta,"
                                  "'prop.position': pos,"
                                  "'prop.update_at': (tim / 1000) | timestamp_local,"
                                  "} }}",
    'mxiang_cateye_cloud_props': "{{ {"
                                 "'battery_level':     props.get('prop.battery_level','0')     | from_json | int,"
                                 "'is_can_open_video': props.get('prop.is_can_open_video','0') | from_json | int,"
                                 "} }}",
    'mxiang_cateye_human_visit_details': "{%- set val = (result.0 | default({})).get('value','{}') %}"
                                         "{%- set val = val | from_json %}"
                                         "{{ {"
                                         "'motion_video_time': val.get('visitTime',0) | timestamp_local,"
                                         "'motion_video_type': val.get('action'),"
                                         "'motion_video_latest': val,"
                                         "'_entity_attrs': True,"
                                         "} }}",
}
