blueprint:
  name: Camera Recording and Notify / æ‘„åƒå¤´æˆ–é—¨é“ƒå½•åƒå¹¶é€šçŸ¥
  description: |
    ### ðŸŽ¦ Guides:
    1. Add the script for saving the video recording / æ·»åŠ ä¿å­˜å½•åƒè„šæœ¬
    ```yaml
    # configuration.yaml
    shell_command:
      # other commands ...
      save_camera_video: |
        bash -c '
          dir="{{ dir|default('/media/camera',true) }}"
          mkdir -p "$dir" && cd "$dir"
          ffmpeg -y -i "{{ url }}" -c copy "{{ name|default('latest') }}.mp4"
          ls *.mp4 | sort | head -n -{{ keep|default(100) }} | xargs rm -vf
          if [ -n "{{ img }}" ]; then
            curl -o "{{ name|default('latest') }}.jpg" "{{ img }}"
            ls *.jpg | sort | head -n -{{ keep|default(100) }} | xargs rm -vf
          fi
        '
    ```
    2. Restart Home Assistant / é‡å¯ Home Assistant

  domain: automation
  input:
    camera:
      name: Camera or Doorbell
      description: é€šè¿‡Xiaomi Mioté›†æˆçš„æ‘„åƒæœºæˆ–é—¨é“ƒå®žä½“
      selector:
        entity:
          domain: camera
          integration: xiaomi_miot

    mihome_notify:
      name: Mihome message entity
      description: ç±³å®¶æ¶ˆæ¯å®žä½“ï¼Œç”¨äºŽå‡å°èŽ·å–å½•åƒçš„å»¶è¿Ÿ `sensor.mi_xxxx_message`
      selector:
        entity:
          domain: sensor
          integration: xiaomi_miot

    mihome_notify_kwd:
      name: Camera name in mihome
      description: æ‘„åƒæœºåœ¨ç±³å®¶ä¸­çš„åç§°(å…³é”®è¯)ï¼Œç”¨äºŽå‡å°èŽ·å–å½•åƒçš„å»¶è¿Ÿ
      selector:
        text:
      default: ''

    notify_device:
      name: Device to notify
      description: |
        Need to install the official Home Assistant app to receive notifications
        éœ€å®‰è£…å®˜æ–¹[Home Assistantåº”ç”¨](https://companion.home-assistant.io)ä»¥æŽ¥æ”¶é€šçŸ¥çš„ç§»åŠ¨è®¾å¤‡
      selector:
        device:
          integration: mobile_app

    notification_title:
      name: Notification title
      description: é€šçŸ¥æ ‡é¢˜
      default: ''

    notification_message:
      name: Notification content
      description: é€šçŸ¥å†…å®¹
      default: ''

    save_dir:
      name: Save dir
      description: ä¿å­˜è·¯å¾„ï¼Œé»˜è®¤ï¼š`/media/camera`
      default: ''

    keep_num:
      name: The number of recorded videos to retain
      description: ä¿ç•™å½•åƒæ•°é‡
      default: 100
      selector:
        number:
            min: 1
            max: 2000
            mode: slider

    external_url:
      name: External url
      description: å¤–éƒ¨è®¿é—®åœ°å€ï¼Œhttps://your.hass.domain:8123
      default: ''

    btn_mihome:
      name: Button text of open in Mihome
      description: æŒ‰é’®æ–‡å­—
      default: æ‰“å¼€ç±³å®¶

    btn_okay:
      name: Button text of Okay
      description: æŒ‰é’®æ–‡å­—
      default: æˆ‘çŸ¥é“äº†

mode: queued
triggers:
  - platform: state
    entity_id: !input camera
    attribute: motion_video_time
    id: new_video
  - platform: state
    entity_id: !input mihome_notify
    id: mihome_notify

variables:
  camera_entity_id: !input camera
  camera_device_id: "{{ device_id(camera_entity_id) }}"
  camera_device_name: "{{ device_attr(camera_device_id,'name') }}"
  camera_info_id: "{{ device_entities(camera_device_id) | select('match','button.+_info') | join }}"
  mihome_notify_kwd: !input mihome_notify_kwd
  mihome_notify_name: "{{ mihome_notify_kwd or camera_device_name }}"
  save_dir: !input save_dir
  save_url: "{{ save_dir | replace('/media/','/media/local/') | replace('/config/www','/local') }}"
  external_url: !input external_url
  notification_title: !input notification_title
  notification_message: !input notification_message

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: mihome_notify
          - condition: template
            value_template: "{{ mihome_notify_name in trigger.to_state.state }}"
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id: "{{ camera_entity_id }}"

      - conditions:
          - condition: trigger
            id: new_video
        sequence:
          - variables:
              stream_url: "{{ state_attr(camera_entity_id,'stream_address')}}"
              motion_video_time: >-
                {{ state_attr(camera_entity_id,'motion_video_time')|regex_replace('[\s:+-]','') }}
              motion_video_type: >-
                {{ state_attr(camera_entity_id,'motion_video_type')|regex_replace('[\s:+-]','') }}
              mp4_name: "{{ motion_video_time }}-{{ motion_video_type }}"
              mp4_path: "{{ save_url }}/{{ mp4_name }}.mp4"
              img_path: "{{ (external_url~state_attr(camera_entity_id,'entity_picture')) if external_url else '' }}"
          - action: shell_command.save_camera_video
            data:
              name: "{{ mp4_name }}"
              dir: "{{ save_dir }}"
              img: "{{ img_path }}"
              url: "{{ stream_url }}"
              keep: !input keep_num
            response_variable: action_result
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "{{ notification_title or camera_device_name }}"
            message: "{{ notification_message }}"
            data:
              image: "{{ img_path }}"
              video: "{{ mp4_path }}"
              url: /config/devices/device/{{ camera_device_id }}
              actions:
                - action: URI
                  title: !input btn_mihome
                  uri: "{{ state_attr(camera_info_id,'app_link') }}"
                - action: none
                  title: !input btn_okay
              push:
                tag: "{{ camera_entity_id }}"