name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/xiaomi_miot
          zip -r xiaomi_miot.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/xiaomi_miot/xiaomi_miot.zip
          asset_name: xiaomi_miot.zip
          tag: ${{ github.ref }}
          overwrite: true
